import { IUsers } from '@/models/user.model';

const dummyData: IUsers[] = [
  {
    _id: undefined,
    email: 'john.doe1@example.com',
    phoneNumber: '09459840001',
    password: 'hashed_password_1',
    agreeToTerms: true,
    isRecruiter: false,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    cinPanGst: '',
    companyEmail: '',
    officeEmail: '',
    remarks: 'Test user 1',
    favouriteCourses: ['course1', 'course2'],
    id: 'user1',
  },
  {
    email: 'jane.doe2@example.com',
    phoneNumber: '09459840002',
    password: 'hashed_password_2',
    agreeToTerms: true,
    isRecruiter: false,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    remarks: 'Test user 2',
    id: 'user2',
  },
  {
    email: 'bob.smith3@example.com',
    phoneNumber: '09459840003',
    password: 'hashed_password_3',
    agreeToTerms: true,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    cinPanGst: 'CIN1234567',
    id: 'user3',
  },
  {
    email: 'alice.jones4@example.com',
    phoneNumber: '09459840004',
    password: 'hashed_password_4',
    agreeToTerms: true,
    isRecruiter: true,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    favouriteCourses: ['course3'],
    id: 'user4',
  },
  {
    email: 'charlie.brown5@example.com',
    phoneNumber: '09459840005',
    password: 'hashed_password_5',
    agreeToTerms: true,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    officeEmail: 'office5@example.com',
    id: 'user5',
  },
  {
    email: 'emily.white6@example.com',
    phoneNumber: '09459840006',
    password: 'hashed_password_6',
    agreeToTerms: true,
    isRecruiter: false,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    companyEmail: 'company6@example.com',
    remarks: 'VIP',
    id: 'user6',
  },
  {
    email: 'frank.thomas7@example.com',
    phoneNumber: '09459840007',
    password: 'hashed_password_7',
    agreeToTerms: true,
    isVerified: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    id: 'user7',
  },
  {
    email: 'grace.lee8@example.com',
    phoneNumber: '09459840008',
    password: 'hashed_password_8',
    agreeToTerms: true,
    isRecruiter: true,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    id: 'user8',
  },
  {
    email: 'henry.moore9@example.com',
    phoneNumber: '09459840009',
    password: 'hashed_password_9',
    agreeToTerms: true,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    favouriteCourses: ['course1', 'course5'],
    id: 'user9',
  },
  {
    email: 'isabella.king10@example.com',
    phoneNumber: '09459840010',
    password: 'hashed_password_10',
    agreeToTerms: true,
    isRecruiter: false,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    cinPanGst: 'GST99999',
    officeEmail: 'isabella.office@example.com',
    id: 'user10',
  },
];

export default dummyData;
